### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Remove Account' (delete-account-async)

### ISSUE THREAD

**Issue by RRLatFlinders** [sailpoint-oss/developer.sailpoint.com#745]
The permissions scope suggested on this API call does not exist (idn:account:remove). Do you perhaps mean idn:accounts:manage ?
Also of note, the BETA API specifications have the same error.

![Image](https://github.com/user-attachments/assets/9f92145e-f1a9-4ecf-a1d6-199400301669)

**Comment by darrell-thobe-sp** [comment]
Thank you @RRLatFlinders for brining this issue to our attention. this should be updated and resolved with commit [d60817a7b616cb4534ad6ed8c3aa4bd70cc3add2](https://github.com/sailpoint-oss/developer.sailpoint.com/commit/d60817a7b616cb4534ad6ed8c3aa4bd70cc3add2)

**Comment by RRLatFlinders** [comment]
Hi @darrell-thobe-sp I've just checked the documentation and the scope listed in v2024 for /remove is idn:account:manage which is incorrect - correct scope is idn:accounts:manage (missing the s on accounts). I haven't checked the other related API calls, I assume they're likely the same.

**Comment by RRLatFlinders** [comment]
Hi Darrell,

Unfortunately, this one isn't fixed - I've added a note to the ticket already with details.


Thank you,



Raphael



Raphael Russell-Livingstone
Senior Identity Operations Specialist
Information Security and Identity

Information and Digital Services

www.flinders.edu.au/people/raphael.russelllivingstone<http://www.flinders.edu.au/people/raphael.russelllivingstone>

[FlindersUniversity]

Sturt Road, Bedford Park SA 5042
GPO Box 2100 Adelaide SA 5001
+61 8 8201 2608

flinders.edu.au<https://flinders.edu.au/>

Flinders University acknowledges the Traditional Owners and Custodians of the lands on which its campuses are located, these are the Traditional Lands of the Arrernte, Dagoman, First Nations of the South-East, First Peoples of the River Murray & Mallee region, Jawoyn, Kaurna, Larrakia, Ngadjuri, Ngarrindjeri, Ramindjeri, Warumungu, Wardaman and Yolngu people. We honour their Elders past, present and emerging.

CRICOS Provider Number: 00114A This email and any attachments may be confidential. If you are not the intended recipient, please inform the sender by reply email and delete all copies of this message.

Please consider the environment before printing this email.


________________________________
